server:
  http:
    name: demo
    addr: ":8080"
    server_config:
      read_timeout: 10
      write_timeout: 15
      read_header_timeout: 12
      idle_timeout: 8
mysql:
  default:
    dsn: "username@tcp(127.0.0.1:3306)/dev?charset=utf8"
    is_debug: "true"